- name: Create a user on Linux Servers
  hosts: linux
  tasks:
  - name: Create jenkins user
    user:
      name: sysadmin
      state: present
  - name: createing group for terraform
    group:
      name: production
      state: present    
  - name: create a user for terraform
    user:
      name: dev1
      groups: terra
      state: present     
